name: Transfer to Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Transfer to Azure Blob Storage
        uses: Azure/blobxfer@1.5.5
        with:
          storage_account: aksummasa
          storage_account_key: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
          container_name: container
          local_path: ./scenarios.json
          blob_path: /container/myblob.json
